kind: "Service"
apiVersion: "v1"
metadata:
  labels:
    app: "event-handler-archived"
  name: "event-handler-archived-qas"
  namespace: "vrt-intake"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: event-handler-archived-qas
